### ISSUE TITLE
create sample data

### ISSUE THREAD

**Issue by joshuago78** [gri-is/dana#2]
- talk to Rob about IIIF endpoint
- find sample collection, images

**Comment by alyxrossetti** [comment]
So I think I am going to use a subset of Clark Duveen IIIF docs as test data.  Do we know how much data we want? @joshuago78

**Comment by joshuago78** [comment]
I would guess at least two series, each with at least two subseries? And within those a mix of digital and non-digital components. I imagine we will want something more than that eventually, but that may be enough to start.
