### ISSUE TITLE
Show Series Header

### ISSUE THREAD

**Issue by nathanieldeines** [gri-is/dana#46]
![screen shot 2017-05-11 at 4 53 53 pm copy](https://cloud.githubusercontent.com/assets/16109511/25976561/b8938dec-366a-11e7-8016-1c766738a99a.png)

**Comment by nathanieldeines** [comment]
Assigning to @kristenGRI for review.

**Comment by kristenGRI** [comment]
This seems to be pulling all the proper information but I have two thoughts.
1. For series that don't have sub series (Series I, II, and X) it seems their header should be placed below the Collection header and not above the contents of collection (where it's currently appearing)
**Series I:** http://dana-qa.getty.edu/#/collections/2011m30/series/2011m30_ref5903_vld/
![series i](https://user-images.githubusercontent.com/15019503/28385115-c611b3bc-6c7b-11e7-9601-ec67ce81acd7.png)
**Series III:** http://dana-qa.getty.edu/#/collections/2011m30/series/2011m30_ref234485_6io/subseries/2011m30_ref234488_uf9

![series iii](https://user-images.githubusercontent.com/15019503/28385158-e43d58fa-6c7b-11e7-93d6-8d608c346a54.png)

2. Did we decide to switch the placement of the series number and series title? Currently in QA it says "Curator and museum professional files, Series III." It the current Finding Aid it says "Series III. Curator and museum professional files"
