### ISSUE TITLE
Collapsible / Expandable Parent Items

### ISSUE THREAD

**Issue by nathanieldeines** [gri-is/dana#50]
![screen shot 2017-05-11 at 5 05 16 pm](https://cloud.githubusercontent.com/assets/16109511/25976799/0d1de1ae-366c-11e7-8ef9-2128bdcb4cf3.png)

**Comment by nathanieldeines** [comment]
Assigning to Kristen for review.

**Comment by kristenGRI** [comment]
This doesn't seem to be implemented. For example, if you go to series IV, look for "Live in Your Head" this is a parent item that should have Black-and-white photographs, Color transparencies, Opening, Michael Heizer, etc in it. Michael Heizer should also have children. Currently it looks like only top level items are being pulled.

http://dana-qa.getty.edu/#/collections/2011m30/series/2011m30_ref13_0pf/subseries/2011m30_ref15_1je
