### ISSUE TITLE
Sub-Series Title

### ISSUE THREAD

**Issue by nathanieldeines** [gri-is/dana#51]
![screen shot 2017-05-11 at 5 07 49 pm copy](https://cloud.githubusercontent.com/assets/16109511/25976875/81807c50-366c-11e7-86de-f4bb9cf1fdc3.png)

**Comment by nathanieldeines** [comment]
Assigning to Kristen for review.

**Comment by kristenGRI** [comment]
This looks good. The only thing that needs to be done yet is making sure the sub series is sticky to the top of the page when the user scrolls down. Not sure if this will be done when we start styling or if it was just missed as part of this phase.

**Comment by nathanieldeines** [comment]
Assigning to @rit  to implement @kristenGRI's changes.
