### ISSUE TITLE
Hierarchical navigation sidebar

### ISSUE THREAD

**Issue by nathanieldeines** [gri-is/dana#60]
![screen shot 2017-05-11 at 5 40 20 pm copy 2](https://cloud.githubusercontent.com/assets/16109511/25977584/5666fb5c-3671-11e7-8a37-297a1efe6d4f.png)

**Comment by nathanieldeines** [comment]
Assigning to Kristen for review.

**Comment by kristenGRI** [comment]
This has been built and looks to function per the design except one thing. 

When I click on a top tier item that has children, the entire section doesn't load. Example: 
1. Load http://dana-qa.getty.edu/#/collections/2011m30/
2. Click Photographs, Series IV.
Notice it only expands the accordion and does not load all its children's content. Once this is fixed, this should be good to go.

**Comment by nathanieldeines** [comment]
Assigning to @rit to implement @kristenGRI's updates.
