### ISSUE TITLE
Sub-series header in the Main Body

### ISSUE THREAD

**Issue by joshuago78** [gri-is/dana#7]
![screen shot 2017-05-11 at 4 41 31 pm](https://cloud.githubusercontent.com/assets/16109511/25976305/e04d62d8-3668-11e7-885f-736ede48558c.png)

**Comment by nathanieldeines** [comment]
Assigning to Kristen for review.

**Comment by kristenGRI** [comment]
This seems to be pulling the correct information and displaying where it should. But I have a similar notes as ticket #46.
- Did we decide to switch the placement of the series number and series title? Currently in QA it says "Curator and museum professional files, Series V.C." It the current Finding Aid it says "Series V.C. Curator and museum professional files"

http://dana-qa.getty.edu/#/collections/2011m30/series/2011m30_ref240273_o72/subseries/2011m30_ref245418_3ea
