### ISSUE TITLE
Manifest Detail: Navigate Manifest: Build a list of ranges

### ISSUE THREAD

**Issue by kristenGRI** [gri-is/dana#71]
On the manifest detail page, there should be a list of ranges that appear below Mirador. In the example attached, Black-and-white photographs, Color transparencies, Slide carousel, etc, are all rangest inside the "Live in Your Head: When Attitudes Become Form, 1969 manifest.

Image attached. Full comp can be found here:
https://share.getty.edu/download/attachments/90046549/DANA_ItemDetail_SeriesIV.jpg?api=v2
<img width="945" alt="screen shot 2017-08-02 at 5 09 56 pm" src="https://user-images.githubusercontent.com/15019503/28900426-f468c284-77a5-11e7-95aa-d7fb78515414.png">

**Comment by rit** [comment]
@kristenGRI could you please provide:

- [ ] the plus and minus icon
- [ ] the hex value of the background color

**Comment by nathanieldeines** [comment]
Assigning to KC for review.

**Comment by kristenGRI** [comment]
This is functioning as expected. Verified on dana-qa.getty.edu on Chrome, FF, and Safari with example of test case:
http://dana-qa.getty.edu/#/collections/2011m30/objects/2011m30_ref450_nar

Hex numbers for colors and iconography have been put in ticket #80 

Closing.
