### ISSUE TITLE
Manifest Detail: Navigate Manifest: Build Sub-Sub Ranges 

### ISSUE THREAD

**Issue by kristenGRI** [gri-is/dana#73]
On the manifest detail page, if a sub-range has a range, we'll need a sub-sub range display.

In the example attached, Black-and-white photographs has the sub-sub ranges of Item 1, Item 2, etc while Black-and-white negatives do not. Sub-Sub range titles will appear above the image thumbs while the image titles will remain below.

Image attached. Full comp can be found here:
https://share.getty.edu/download/attachments/90046549/DANA_ItemDetail_SeriesIV_Open%20Component.jpg?api=v2
<img width="1200" alt="screen shot 2017-08-02 at 5 21 45 pm" src="https://user-images.githubusercontent.com/15019503/28904169-de9406f4-77bd-11e7-87e9-c990f12a92f2.png">

**Comment by nathanieldeines** [comment]
Assigning to KC for review. When tickets are done, please assign to KC for review. Thanks.

**Comment by kristenGRI** [comment]
This is functioning as expected. Verified on dana-qa.getty.edu on Chrome, FF, and Safari with example of test case:
http://dana-qa.getty.edu/#/collections/2011m30/objects/2011m30_ref450_nar

Closing.
