### ISSUE TITLE
Bug: Safari: Image thumbs for ranges are missing or sometimes overlapping

### ISSUE THREAD

**Issue by kristenGRI** [gri-is/dana#82]
1. Go to http://dana-qa.getty.edu/#/collections/2011m30 in Safari (I was running Version 9.1.2)
2. Navigate to manifest detail page with images (ex: http://dana-qa.getty.edu/#/collections/2011m30/objects/2011m30_ref450_nar)
3. Open up the ranges and look at the image thumbs for the sub-ranges

Bug: The images are missing (ex: Black and white photographs) or sometimes overlapping (ex: Michael Heizer) Note that these are not the only ranges in this manifest that experience this bug.

See screenshots

Black-and-white-photographs
<img width="1211" alt="screen shot 2017-08-25 at 2 57 19 pm" src="https://user-images.githubusercontent.com/15019503/29734471-3d17e1dc-89a7-11e7-8f73-6492c8e4f87d.png">

Michael Heizer
<img width="1312" alt="screen shot 2017-08-25 at 3 09 06 pm" src="https://user-images.githubusercontent.com/15019503/29734514-761629c6-89a7-11e7-92dc-d6a306cb8117.png">

**Comment by rit** [comment]
@kristenGRI The problem has to with Safari's support of Flexbox. I've updated the code so it adds safari specific prefixes. It works on Safari 10.1.2.

**Comment by kristenGRI** [comment]
This is fixed. Verified on the most recent version of Safari, 10.1.2
http://dana-qa.getty.edu/#/collections/2011m30/objects/2011m30_ref234462_3rn

Closing.
