### ISSUE TITLE
Add high-level collection metadata to descriptive summary and extent slideout.

### ISSUE THREAD

**Issue by kristenGRI** [gri-is/dana#87]
If you go to the current finding aid, you'll notice there is a lot of metadata listed for the collection:
http://archives2.getty.edu:8082/xtf/view?docId=ead/2011.M.30/2011.M.30.xml;chunk.id=headerlink;brand=default

This was going to be tackled with a collection specific navigation that would replace the archive view with a static page where this information would be populated. (image below of this navigation)
![screen shot 2017-09-13 at 5 54 00 pm](https://user-images.githubusercontent.com/15019503/30407347-9d510718-98ac-11e7-9b95-cc9222f490e7.png)

Since we are down to the wire, please add the information to the current slide out for the Szeemann collection summary and extent. The information that should be included: should be everything in:

- Descriptive Summary 
(http://archives2.getty.edu:8082/xtf/view?docId=ead/2011.M.30/2011.M.30.xml;chunk.id=headerlink;brand=default)

- Biographical / Historical Notes 
(http://archives2.getty.edu:8082/xtf/view?docId=ead/2011.M.30/2011.M.30.xml;chunk.id=aspace_05ae314f412507c5248825502613823d;brand=default)

- Scope and Content of Collection
http://archives2.getty.edu:8082/xtf/view?docId=ead/2011.M.30/2011.M.30.xml;chunk.id=scopecontent_1;brand=default

- Restrictions
http://archives2.getty.edu:8082/xtf/view?docId=ead/2011.M.30/2011.M.30.xml;chunk.id=restrictlink;brand=default

- Indexing Terms
http://archives2.getty.edu:8082/xtf/view?docId=ead/2011.M.30/2011.M.30.xml;chunk.id=controlaccess_1;brand=default

- Related Material
http://archives2.getty.edu:8082/xtf/view?docId=ead/2011.M.30/2011.M.30.xml;chunk.id=relatedmatlink;brand=default

- Administrative Information
http://archives2.getty.edu:8082/xtf/view?docId=ead/2011.M.30/2011.M.30.xml;chunk.id=adminlink;brand=default

**Comment by alyxrossetti** [comment]
@kristenGRI Should this data be added to the "More Info" slideout on the detail pages too?

**Comment by kristenGRI** [comment]
@alyxrossetti Correct. It should technically be the same slideout so it should have all the same info.

**Comment by kristenGRI** [comment]
As far as I can tell, all the information is not in the slideout for the collection. Closing.
